name: nagraj_utils
description: Just first package.
version: 0.0.2
repository: https://github.com/nagraj0308/nagraj_utils

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

